Repository BigData23th/DataAnalysis, pull requests merged in 2023-03, with the labels that each got.

#3 03/08 회고
  whataLIN/README.md
  whataLIN/ch05/ch05_01_numpy_기초.ipynb
  whataLIN/ch05/ch05_02_배열의_생성과_변형.ipynb
Labels: KPT, 필기

#4 2023.03.08(회고)
  hiid0726/ch05_01_numpy_기초_ym.ipynb
  hiid0726/ch05_02_배열의_생성과_변형_ym_1.ipynb
Labels: 4줄일기, 필기

#5 Day 07 회고
  Myun9hyun/ch05_01_numpy_기초.ipynb
  Myun9hyun/ch05_02_배열의_생성과_변형_Myun9hyun.ipynb
Labels: STAR, 필기

#6 2023.03.08 회고
  ch05_01_numpy_기초_sdj.ipynb
  ch05_02_배열의_생성과_변형_sdj.ipynb
Labels: KPT, 필기

#7 230308 회고
  tkd8973/230308_Numpy.ipynb
Labels: KPT, 필기

#8 3월 8일 7일차 회고
  Yeaaaaaaah/ch05_01_numpy_기초.ipynb
Labels: KPT, 필기

#9 2023/03/08 수업
  JoySoon/ch05_01_numpy_기초_KSW.ipynb
  JoySoon/ch05_02_배열의_생성과_변형_KSW_ipynb강성욱.ipynb
Labels: 4줄일기, 필기

#10 03-08 회고
  DataAnalysis/Kwak/numpy/ch05_01_numpy_기초_kwak99_ipynb의_사본.ipynb
Labels: KPT, 필기

#11 0308
  andy9806/0308.ipynb
Labels: STAR

#12 2023_03_08_회고
  cc5547/2023_03_08_ch05_01_numpy_기초.ipynb
  cc5547/2023_03_08_ch05_02_배열의_생성과_변형.ipynb
Labels: 4줄일기, 필기

#13 2023.03.08
  zihvvan/ch05_01_numpy_기초.ipynb
  zihvvan/ch05_02_배열의_생성과_변형.ipynb
Labels: KPT, 필기

#14 23.03.08 회고
  mastgm0817/Ch05/ch05_01_numpy_기초.ipynb
  mastgm0817/Ch05/ch05_02_배열의_생성과_변형.ipynb
Labels: 4줄일기, 필기

#16 23.03.08 회고
  CHOISEONGGU/공부/ch05_01_numpy_기초_ChoiSG.ipynb
  CHOISEONGGU/공부/ch05_02_배열의_생성과_변형_ChoiSg.ipynb
  CHOISEONGGU/복습/ch05_02_배열의_생성과_변형_ChoiSg.ipynb
Labels: 4줄일기, 필기

#18 2023.03.08 회고
  suhdongjoon/ch05_01_numpy_기초_sdj.ipynb
  suhdongjoon/ch05_02_배열의_생성과_변형_sdj.ipynb
Labels: KPT, 필기

#19 day7
  jyeongvv/ch05_01+02_복습.ipynb
  jyeongvv/ch05_01_numpy_기초.ipynb
  jyeongvv/ch05_02_배열의_생성과_변형.ipynb
  jyeongvv/ch05_02_배열의_생성과_변형2.ipynb
  jyeongvv/ch05_03_배열의_연산.ipynb
  jyeongvv/ch05_04_기술통계+난수발생과+카운팅.ipynb
Labels: 4줄일기, 필기

#20 7일차 회고
  jaiwon880/ch05_01_numpy_기초.ipynb
  jaiwon880/ch05_02_배열의_생성과_변형.ipynb
  jaiwon880/ch05_02_배열의_생성과_변형2.ipynb
  jaiwon880/ch05_03_배열의_연산.ipynb
Labels: STAR, 필기

#23 0309회고
  sunghuncho/ch05_01+02_복습.ipynb
  sunghuncho/ch05_02_배열의_생성과_변형(완)_sunghuncho.ipynb
  sunghuncho/ch05_03_배열의_연산_sunghuncho.ipynb
  sunghuncho/ch05_04_기술통계+난수발생과+카운팅_sunghuncho.ipynb
Labels: 4줄일기, 필기

#24 23.03.09 회고
  CHOISEONGGU/공부자료/ch05_01_numpy_기초_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch05_02_01_배열의_생성과_변형_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch05_02_02_배열의_생성과_변형_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch05_03_배열의_연산_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch05_04_기술통계+난수발생과+카운팅_ChoiSG.ipynb
  CHOISEONGGU/복습/ch05_01+02_복습.ipynb
Labels: 4줄일기, 필기

#26 2023.03.09(회고)
  hiid0726/ch05_01+02복습.ipynb
  hiid0726/ch05_02+03+04복습.ipynb
  hiid0726/ch05_02_배열의_생성과_변형_ym.ipynb
  hiid0726/ch05_03_배열의_연산_ym.ipynb
  hiid0726/ch05_04_기술통계+난수발생과+카운팅_ym.ipynb
Labels: 4줄일기, 필기

#27 2023/03/09 수업
  JoySoon/ch05_02_배열의_생성과_변형_2_KSW.ipynb
  JoySoon/ch05_03_배열의_연산_KSW.ipynb
  JoySoon/ch05_04_기술통계+난수발생과+카운팅_KSW.ipynb
Labels: 4줄일기, 필기

#28 23.03.09 회고
  mastgm0817/ch05_01+02_복습.ipynb
  mastgm0817/ch05_01_numpy_기초.ipynb
  mastgm0817/ch05_02_배열의_생성과_변형.ipynb
  mastgm0817/ch05_03_배열의_연산.ipynb
Labels: 4줄일기, 필기

#29 23.03.09 회고
  Myun9hyun/ch05_01+02_복습_Myun9hyun.ipynb
  Myun9hyun/ch05_02+03+04_복습.ipynb
  Myun9hyun/ch05_02_배열의_생성과_변형_Myun9hyun.ipynb
  Myun9hyun/ch05_03_배열의_연산_Myun9hyun.ipynb
  Myun9hyun/ch05_04_기술통계+난수발생과+카운팅_Myun9hyun.ipynb
Labels: 4줄일기, 필기

#30 23.03.09 수업 회고
  JaejinLee1215/ch05_02+03+04_복습.ipynb
  JaejinLee1215/ch05_03_배열의_연산_이재진.ipynb
Labels: STAR, 필기

#31 8일차 회고
  jaiwon880/ch05_04_기술통계+난수발생과+카운팅.ipynb
Labels: KPT, 필기

#32 0310회고
  sunghuncho/ch05_02+03+04_복습_sunghuncho.ipynb
  sunghuncho/ch06_01_pandas_기초_sunghuncho.ipynb
Labels: 4줄일기, 필기

#33 3월 10일 9일차 회고
  Yeaaaaaaah/ch05_02_배열의_생성과_변형.ipynb
  Yeaaaaaaah/ch05_03_배열의_연산.ipynb
  Yeaaaaaaah/ch05_04_기술통계+난수발생과+카운팅.ipynb
  Yeaaaaaaah/ch06_01_pandas_기초.ipynb
  submission/Yeaaaaaaah/복습용/ch03_03_예외처리_qus0in.ipynb
  submission/Yeaaaaaaah/복습용/ch04_02_날짜와_시간_qus0in.ipynb
Labels: 4줄일기, 필기

#35 2023.03.10
  zihvvan/ch05_01+02_복습.ipynb
  zihvvan/ch05_02+03+04_복습.ipynb
  zihvvan/ch05_02_배열의_생성과_변형.ipynb
  zihvvan/ch05_03_배열의_연산.ipynb
  zihvvan/ch05_04_기술통계+난수발생과+카운팅.ipynb
  zihvvan/ch06_01_pandas_기초.ipynb
Labels: 4줄일기, 필기

#36 03/10 회고
  ch05_02_배열의_생성과_변형.ipynb
  ch05_03_배열의_연산.ipynb
  ch06_01_pandas_기초.ipynb
Labels: KPT, 필기

#37 230309, 230310 회고
  tkd8973/Pandas_기초.ipynb
Labels: KPT, 필기

#38 03-10회고
  kwak/ch06_01_pandas_기초_wa9_ipynb의_사본.ipynb
Labels: KPT, 필기

#43 03-10 회고
  Myun9hyun/ch06_01_pandas_기초_Myun9hyun.ipynb
Labels: KPT, 필기

#39 2023_03_10_회고
  cc5547/2023_03_09_ch05_01+02_복습.ipynb
  cc5547/2023_03_09_ch05_02_배열의_생성과_변형.ipynb
  cc5547/2023_03_09_ch05_03_배열의_연산.ipynb
  cc5547/2023_03_10_ch05_02+03+04_복습.ipynb
  cc5547/2023_03_10_ch06_01_pandas_기초.ipynb
Labels: 4줄일기, 필기

#41 2023.03.10
  hiid0726/ch06_01_pandas_기초_ym.ipynb
Labels: 4줄일기, 필기

#42 9일차 회고
  jaiwon880/ch05_02+03+04_복습.ipynb
  jaiwon880/ch06_01_pandas_기초.ipynb
Labels: KPT, 필기

#44 2023/03/10
  JoySoon/ch06_01_pandas_기초_KSW.ipynb
Labels: KPT, 필기

#45 2023.03.10 회고
  mastgm0817/ch05_02+03+04_복습.ipynb
  mastgm0817/ch06_01_pandas_기초.ipynb
Labels: 4줄일기, 필기

#46 23.03.10 수업 회고
  JaejinLee1215/ch05_04_기술통계+난수발생과+카운팅_이재진.ipynb
  JaejinLee1215/ch06_01_pandas_기초_이재진.ipynb
  JaejinLee1215/ch06_01_복습.ipynb
  JaejinLee1215/ch06_02_데이터프레임_조작_이재진.ipynb
Labels: STAR, 필기

#48 2023/03/13
  JoySoon/ch06_02_데이터프레임_조작_KSW.ipynb
  JoySoon/ch06_03_데이터프레임_심화_KSW.ipynb
Labels: 4줄일기, 필기

#49 0313
  andy9806/0313.ipynb
Labels: STAR, 필기

#51 2023.03.13 회고
  hiid0726/ch06_01복습ym.ipynb
  hiid0726/ch06_02_데이터프레임_조작_ym.ipynb
  hiid0726/ch06_03_데이터프레임_심화_ym.ipynb
Labels: 4줄일기, 필기

#52 2023_03_13
  cc5547/2023_03_13_ch06_01_복습.ipynb
Labels: 4줄일기, 필기

#53 2023.03.13
  zihvvan/ch06_01_복습.ipynb
  zihvvan/ch06_02_데이터프레임_조작.ipynb
Labels: 4줄일기, 필기

#54 0313 회고
  sunghuncho/ch06_01_복습.ipynb
  sunghuncho/ch06_02_데이터프레임_조작_sunghuncho.ipynb
  sunghuncho/ch06_03_데이터프레임_심화_sunghuncho(미완).ipynb
Labels: 4줄일기, 필기

#56 03-13 회고
  Myun9hyun/ch06_02_데이터프레임_조작_Myun9hyun.ipynb
Labels: STAR, 필기

#58 23.03.13 수업 회고
  JaejinLee1215/ch06_03_데이터프레임_심화_이재진.ipynb
Labels: STAR, 필기

#59 23.03.13
  CHOISEONGGU/공부자료/ch06_01_pandas_기초_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch06_01_pandas_기초_필기.ipynb
  CHOISEONGGU/공부자료/ch06_02_데이터프레임_조작_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch06_03_데이터프레임_심화_ChoiSG.ipynb
  CHOISEONGGU/복습/ch06_01_복습.ipynb
Labels: 4줄일기, 필기

#60 03/13 회고
  ch05_02_배열의_생성과_변형.ipynb
  whataLIN/ch05/ch05_02_배열의_생성과_변형.ipynb
  whataLIN/ch05/ch05_03_배열의_연산.ipynb
  whataLIN/ch06/ch06_01_pandas_기초.ipynb
  whataLIN/ch06/ch06_02_데이터프레임_조작.ipynb
Labels: KPT, 필기

#62 3월 13일 10일차 회고
  Yeaaaaaaah/ch06_02_데이터프레임_조작.ipynb
  Yeaaaaaaah/ch06_03_데이터프레임_심화.ipynb
  submission/Yeaaaaaaah/복습용/ch03_03_예외처리_qus0in.ipynb
  submission/Yeaaaaaaah/복습용/ch04_02_날짜와_시간_qus0in.ipynb
Labels: 4줄일기, 필기

#63 10일차 회고
  jaiwon880/ch06_01_복습.ipynb
  jaiwon880/ch06_02_데이터프레임_조작.ipynb
  jaiwon880/ch06_03_데이터프레임_심화.ipynb
Labels: KPT, 필기

#65 3월 14일 11일차 회고
  Yeaaaaaaah/ch07_01_시각화_기초.ipynb
Labels: 4줄일기, 필기

#66 03/14 회고
  whataLIN/ch06/ch06_03_데이터프레임_심화.ipynb
  whataLIN/ch07/ch07_01_시각화_기초.ipynb
Labels: 4줄일기, 필기

#68 0314
  andy9806/0314(groupby,agg).ipynb
  andy9806/0314(시각화).ipynb
Labels: STAR, 필기

#69 230313, 230314 회고
  tkd8973/DataFrame_복습.ipynb
  tkd8973/Df_date_time.ipynb
Labels: KPT, 필기

#71 2023.03.14 회고
  hiid0726/ch06_02+03복습.ipynb
  hiid0726/ch06_03_데이터프레임_심화_ym.ipynb
  hiid0726/ch07_01_시각화_기초_ym.ipynb
Labels: 4줄일기, 필기

#72 03-14 회고
  kwak/ch06_02_데이터프레임_조작_wa99_ipynb의_사본.ipynb
  kwak/ch06_03_데이터프레임_심화_wa99_ipynb의_사본.ipynb
  kwak/ch06_04_데이터의_수집_ipynb의_사본.ipynb
  kwak/ch07_01_시각화_기초_wa99_ipynb의_사본.ipynb
Labels: KPT, 필기

#73 11일차 회고
  jaiwon880/ch06_02+03_복습.ipynb
  jaiwon880/ch07_01_시각화_기초.ipynb
Labels: KPT, 필기

#74 23.03.14 회고
  CHOISEONGGU/공부자료/ch06_03_데이터프레임_심화_ChoiSG.ipynb
  CHOISEONGGU/공부자료/ch07_01_시각화_기초_ChoiSG.ipynb
  CHOISEONGGU/복습/ch06_02+03_복습.ipynb
Labels: 4줄일기, 필기

#75 0314회고
  sunghuncho/ch06_02+03_복습_sunghuncho.ipynb
  sunghuncho/ch06_03_데이터프레임_심화_sunghuncho(완)_ipynb.ipynb
  sunghuncho/ch07_01_시각화_기초_sunghuncho(미완).ipynb
Labels: 4줄일기, 필기

#79 2023.03.14 회고
  mastgm0817/ch06_02+03_복습.ipynb
  mastgm0817/ch07_01_시각화_기초.ipynb
Labels: 4줄일기, 필기

#78 23.03.14 수업 회고
  JaejinLee1215/ch06_02+03_복습.ipynb
  JaejinLee1215/ch06_03_데이터프레임_심화_이재진.ipynb
  JaejinLee1215/ch07_01_시각화_기초_이재진.ipynb
Labels: STAR, 필기

#81 2023.03.16 회고
  suhdongjoon/ch05_03_배열의_연산_sdj.ipynb
  suhdongjoon/ch05_04_기술통계+난수발생과+카운팅_sdj.ipynb
  suhdongjoon/ch06_01_pandas_기초_sdj.ipynb
  suhdongjoon/ch06_02_데이터프레임_조작_sdj.ipynb
  suhdongjoon/ch06_03_데이터프레임_심화_sdj.ipynb
  suhdongjoon/ch07_01_시각화_기초_sdj.ipynb
Labels: 4줄일기, 필기
